------------------------------------------------------------------------

title: "Area under disease progressive curve" author: "Hardlife Chinwa" date: "2025-02-13" output: html_document

```{r}
dpc=read.csv("C:/Users/hchin/OneDrive/Atlantic Beach/Documents/PhD/DPhil/Yield_Gap_analysis/AUDPC.csv")
```

```{r}
library(ggplot2)
library(r4pde)
library(tidyverse)
```

```{r}
dpc3 <- dpc |>
  ggplot(aes(t, y)) +
  theme_r4pde()+
  labs(x = "Reproductive stages (R stages)",
       y = "Disease severity (%)")+
  annotate("rect", xmin = dpc$t[1], xmax = dpc$t[2], 
           ymin = 0, ymax = (dpc$y[1]+ dpc$y[2])/2, 
           color = "white", fill = "gray")+
   annotate("rect", xmin = dpc$t[2], xmax = dpc$t[3], 
            ymin = 0, ymax = (dpc$y[2]+ dpc$y[3])/2, 
            color = "white", fill = "gray")+
   annotate("rect", xmin = dpc$t[3], xmax = dpc$t[4], 
            ymin = 0, ymax = (dpc$y[3]+ dpc$y[4])/2,
            color = "white", fill = "gray")+
   annotate("rect", xmin = dpc$t[4], xmax = dpc$t[5], 
            ymin = 0, ymax = (dpc$y[4]+ dpc$y[5])/2, 
            color = "white", fill = "gray")+
   annotate("rect", xmin = dpc$t[5], xmax = dpc$t[6], 
            ymin = 0, ymax = (dpc$y[5]+ dpc$y[6])/2, 
            color = "white",fill = "gray")+
   annotate("rect", xmin = dpc$t[6], xmax = dpc$t[7], 
            ymin = 0, ymax = (dpc$y[6]+ dpc$y[7])/2, 
            color = "white", fill = "gray")+
  geom_line(linewidth = 1)+
  geom_point(size = 3, shape = 16)+
  annotate(geom = "text", x = 6, y = 45,
           label = "AUDPC" , size = 4)
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6))
  dpc3
```

```{r}
dpc=read.csv("C:/Users/hchin/OneDrive/Atlantic Beach/Documents/PhD/DPhil/Yield_Gap_analysis/AUDPC.csv")
```

```{r}
dpc3 <- dpc |>
  ggplot(aes(t, y)) +
  theme_r4pde()+
  labs(x = "Reproductive stages (R stages)",
       y = "Disease severity (%)")+
  annotate("rect", xmin = dpc$t[1], xmax = dpc$t[2], 
           ymin = 0, ymax = (dpc$y[1]+ dpc$y[2])/2, 
           color = "white", fill = "gray")+
   annotate("rect", xmin = dpc$t[2], xmax = dpc$t[3], 
            ymin = 0, ymax = (dpc$y[2]+ dpc$y[3])/2, 
            color = "white", fill = "gray")+
   annotate("rect", xmin = dpc$t[3], xmax = dpc$t[4], 
            ymin = 0, ymax = (dpc$y[3]+ dpc$y[4])/2,
            color = "white", fill = "gray")+
   annotate("rect", xmin = dpc$t[4], xmax = dpc$t[5], 
            ymin = 0, ymax = (dpc$y[4]+ dpc$y[5])/2, 
            color = "white", fill = "gray")+
   annotate("rect", xmin = dpc$t[5], xmax = dpc$t[6], 
            ymin = 0, ymax = (dpc$y[5]+ dpc$y[6])/2, 
            color = "white",fill = "gray")+
   annotate("rect", xmin = dpc$t[6], xmax = dpc$t[7], 
            ymin = 0, ymax = (dpc$y[6]+ dpc$y[7])/2, 
            color = "white", fill = "gray")+
  geom_line(linewidth = 1)+
  geom_point(size = 3, shape = 16)+
  annotate(geom = "text", x = 6, y = 45,
           label = "AUDPC" , size = 4)
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6))
  dpc3
```

```{r}
ggsave("imgs/dpc3.png")
```

```{r}
getwd()
```
